### ISSUE TITLE
[error]subprocess.CalledProcessError

### ISSUE THREAD

**Issue by xiyan-fu** [Angela7126/pyrouge_for_windows#1]
Thanks for your impressive work. 

After I tried to test my results, I met some problem. The errors are : 
`Can't locate DB_File.pm in @INC (you may need to install the DB_File module) (@INC contains: F:\pyrouge-master\pyrouge-master/tools\ROUGE-1.5.5 C:/Perl/site/lib C:/Perl/lib .) at F:\pyrouge-master\pyrouge-master/tools\ROUGE-1.5.5\ROUGE-1.5.5.pl line 178.
BEGIN failed--compilation aborted at F:\pyrouge-master\pyrouge-master/tools\ROUGE-1.5.5\ROUGE-1.5.5.pl line 178.
Traceback (most recent call last):
  File "F:/study/project/pointer-generator-master/run_summarization.py", line 329, in <module>
    tf.app.run()
  File "F:\ANACONDA\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "F:/study/project/pointer-generator-master/run_summarization.py", line 324, in main
    decoder.decode() # decode indefinitely (unless single_pass=True, in which case deocde the dataset exactly once)
  File "F:\study\project\pointer-generator-master\decode.py", line 79, in decode
    results_dict = rouge_eval(self._rouge_ref_dir, self._rouge_dec_dir)
  File "F:\study\project\pointer-generator-master\decode.py", line 224, in rouge_eval
    rouge_results = r.evaluate()
  File "F:\ANACONDA\lib\site-packages\pyrouge\MyRouge155.py", line 373, in evaluate
    rouge_output = check_output(command, shell=True).decode("UTF-8")
  File "F:\ANACONDA\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "F:\ANACONDA\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Perl\\bin\\perl', 'F:\\pyrouge-master\\pyrouge-master/tools\\ROUGE-1.5.5\\ROUGE-1.5.5.pl', '-e', 'F:\\pyrouge-master\\pyrouge-master/tools\\ROUGE-1.5.5\\data', '-c', '95', '-U', '-r', '1000', '-n', '4', '-a', '-m', 'C:\\Users\\64484\\AppData\\Local\\Temp\\tmpzpmhrgms\\rouge_conf.xml']' returned non-zero exit status 2.
`
Although I try to read the code, I still get confused because of the lack of some explanation about arguments. Could you please give me some help? Thanks.

**Comment by Angela7126** [comment]
@xiyan524 Thanks for your attention~
For your question, Have you tried to install "DB_File"  model into your Perl environment?
Inputting "ppm install DB_File" in your command lines and running it will install DB_File model.
PS: When I ran this pyrouge project, it not raise this error. So, actually, I am not sure whether installing "DB_File" model will solve your problem. If it doesn't work or raise other errors, please let me know. I will try to help~ ^_^

**Comment by Angela7126** [comment]
@xiyan524 Are you install the whole pyrouge environment according to the article on http://blog.csdn.net/MerryCao/article/details/73477543 ?
If you follow this instructions and your computer system is win 8 or win 10, you do not need to create and revise  “setting.ini" file as I have written in section 5.3, and you do not need to revise the line 87 of  file MyRouge155.py as I have written in section 5.5.
If you have changed the line 87 in MyRouge155.py, please recover the line 87 as:

self._settings_file = self.__get_config_path()

**Comment by Angela7126** [comment]
@xiyan524  I have just add some comments for the arguments in the code in my CDSN blog.
**system_path**:   the directory where stores automatically generated summaries that your summarization models produced.
**model_path**:  the directory of standard summaries.
**modelpattern**:  the regular expression for the name pattern of your standard summaries.
**systempattern**: the regular expression for the name pattern of your standard summaries.
**config_file_path**: the path where you want to store the rouge_conf.xml file.
**system_idstr**: a list storing the IDs of your automatic summarization models that you want to test, such as ['01','02','03'].

**Comment by xiyan-fu** [comment]
@Angela7126 Thanks for help, but I still met some problem.
I can not install DB_File module. Firstly, I tried to install by ppm. While I use 'ppm install DB_File', it shows 'no missing package to install' . I can not find any useful solution for it. If I open ppm in my computer,it shows DB_File module had been installed, but verified 0 files(confused about this...)
Then I download DB_File-1.840 from website, and put it in my perl lib path. However, it seems like ppm can not recognize it

**Comment by AmyZhangMin** [comment]
> @Angela7126 Thanks for help, but I still met some problem.
> I can not install DB_File module. Firstly, I tried to install by ppm. While I use 'ppm install DB_File', it shows 'no missing package to install' . I can not find any useful solution for it. If I open ppm in my computer,it shows DB_File module had been installed, but verified 0 files(confused about this...)
> Then I download DB_File-1.840 from website, and put it in my perl lib path. However, it seems like ppm can not recognize it

Hello, I'm troubled by this problem these days, too. Has it been solved now? Could you please help me to solve it?

**Comment by Angela7126** [comment]
@xiyan524 @AmyZhangMin Please try to copy this package in your project directly as the figure below, and see whether it will help.
you can call the MyRouge155 as:
`from pyrouge import MyRouge155`
![image](https://user-images.githubusercontent.com/12032225/49349812-5a707d80-f6e7-11e8-92c4-e65f4177db6b.png)

**Comment by AmyZhangMin** [comment]
@Angela7126 Thank you. But after I tried this method, I met another problem similar to the first one.
`subprocess.CalledProcessError: Command '['D:\\Strawberry\\perl\\bin\\perl', 'D:\\pyrouge\\tools\\ROUGE-1.5.5\\ROUGE-1.5.5.pl', '-e', 'D:\\pyrouge\\tools\\ROUGE-1.5.5\\data', '-c', '95', '-U', '-r', '1000', '-n', '4', '-a', '-m', 'C:\\Users\\YangYang\\AppData\\Local\\Temp\\tmpxu2daenj\\rouge_conf.xml']' returned non-zero exit status 2.`
Then, I copy this command('D:\Strawberry\perl\bin\perl D:\pyrouge\tools\ROUGE-1.5.5\ROUGE-1.5.5.pl -e D:\pyrouge\tools\ROUGE-1.5.5\data -c 95 -U -r 1000 -n 4 -a -m C:\Users\YangYang\AppData\Local\Temp\tmpxu2daenj\rouge_conf.xml') and paste it in cmd.exe, it can be executed successfully and print rouge scores. 
I'm now confused.

**Comment by xiongma** [comment]
@Angela7126  Did you solve this? I have same problem as this.
